fortunas = [
"Tu waifu se volvera lesbiana.",
"El de arriba es puto y el de abajo es su novio.",
"Eres gay solo que no lo aceptas.",
"Seras un heroe.",
"Ma\xf1ana te convertiras en mona china.",
"No podras entender lo que no comprendes.",
"Te tocara una fortuna bien pendeja.",
"Un dia por curiosidad te vestiras de mujer y te va a gustar :3",
"El due\xf1o del server te  la metera por el culo",
"Dejaras de ser travesti.",
"Te gustaran las mujeres de una buena vez",
"**__Esta fortuna te da un ban automatico.__**",
"Ganaras la confianza del due\xf1o del server.",
"Dejaras de ser virgen",
"Te desvirgaran en grupo",
"A\xf1o\xf1a",
"Sida? No te preocupes!! ~~te vas a morir virgen~~",
"Tu hermanita esta embarazada, pero no es tuyo",
"Van a cancelar tus monas chinas favoritas",
"Ma\xf1ana vas a coger si no te dan asco los gatos muertos",
"Ayer tenias que conocer a tu media naranja, ya ni la busques jeje",
"Los judios se van a quedar con tus propiedades",
"Te vas a morir en la tercera guerra mundial",
"Ganaras muchos bitcoins pero te los van a robar",
"**Nunca seras mujer!**",
"Nunca sabrás de que lado masca la iguana",
"Encontraras un gloryhole con tu papá del otro lado",
"Mas vale pájaro en mano que cida en el ano",
"Ocho por ocho ya te pique el bizcocho",
"Eres el mas pendejo del Server",
"Saldrás en la radio, cómo nota de policía",
"El fbi encontro tu cp, ya vales verga compa",
"No tienes fortuna, solo desgracia",
"Dejarás de ser virgen, pero del culo.",
"Seras un Youtuber famoso",
"Tu waifu se volverá 3D, solo que se volverá futa.",
"No tienes fortuna pero oye, al menos no eres Doom.",
"Como eres muy idiota para las finanzas, terminarás viviendo a base de semen debajo de un puente.",
"Aprenderás a usar el texto verde.",
"No tienes fortuna, solo desgracia ;_;",
"No imbécil, nunca aprenderás japonés.",
"*You are already dead.*",
"Conseguirás un sugar daddy. :3",
"Nunca serás bueno dibujando anatomía.",
"Perderás una apuesta y descrubriás que te gustan los penes.",
"Nunca aprenderás a correr como Naruto.",
"La única mujer que se fijará en ti tiene pene.",
"Serás la mano derecha de Kim Jong Un.",
"Jamás serás como Shadman.",
"Te convertirás en el saquito de semen de un proxeneta de tu zona.",
"Encontrarás la cura para los furrys.",
"No, **jamás serás un personaje de anime**",
"Lograrás demostrar que los universos paralelos existen pero quedarás atrapado en el de tu anime preferido (implicando que quieras salir)",
"Aprenderás a usar este bot.~~oye! no es tan dificil~~",
"Felix Argyle te morderá el pene.",
"Lograrás pasar el templo del agua del ocarina del tiempo."
"Serás tan irrelevante que serás la excepción de la regla 34 y 35.",
"Lograrás que en tu país te permitan cambiar tu nombre por uno japonés.",
"Aprenderás a hacer el caramelldansen.",
"Descubrirás que 4chan no está en la deep web.",
"La chica que te gusta te mandará porno de ella solo para mostrarte que tiene pene (y te va a gustar)",
"Dejarás de masturbarte con dibujitos de Sonic.",
"Serás apátrido por traición a la patria por casarte con una burra.",
"Escadidle escadudle, tu pito ahora es un fideo.",
"Entenderás una referencia de los jojos.",
"Tratarás de cogerte un delfín pero llamará al resto y te violarán en grupo.",
"Le darás un buen succ al creador de este bot.",
"Dejarás de tenerle miedo a los payasos.",
"Comprarás un rifle para callar de una buena vez el reggaetton de tu vecino.",
"Crearás un  género de hentai el cuál los legisladores y senadores no sabrán si hacerlo ilegal o no.",
"Tendrás sentimientos encontrados con el caballo del vecino.",
"Te usarán como argumento irrefutable para legalizar el aborto.",
"Perderás una demanda porque logran demostrar tu homosexualidad.",
"Despertarás del sueño y saldrás a socializar.",
"Chris Chan te ganará en una pelea cuerpo a cuerpo.",
"Esta fortuna te causa un ban automático, hasta nunca.",
"Tendrás un sueño donde terminas como la esclava sexual de un demonio en el Infierno, solo que no es un sueño ya que moriste mientras dormías, ahora estarás condenado a tragarte su semen por el resto de la eternidad."
]

