fortunas = [
"Tu waifu se volvera lesbiana.",
"El de arriba es puto y el de abajo es su novio.",
"Eres gay solo que no lo aceptas.",
"Seras un heroe.",
"Ma\xf1ana te convertiras en mona china.",
"No podras entender lo que no comprendes.",
"Te tocara una fortuna bien pendeja.",
"Un dia por curiosidad te vestiras de mujer y te va a gustar :3",
"El due\xf1o del server te  la metera por el culo",
"Dejaras de ser travesti.",
"Te gustaran las mujeres de una buena vez",
"Esta fortuna te da un ban automatico.",
"Ganaras la confianza del due\xf1o del server.",
"Dejaras de ser virgen",
"Te desvirgaran en grupo",
"A\xf1o\xf1a",
"Sida? No te preocupes!! te vas a morir virgen",
"Tu hermanita esta embarazada, pero no es tuyo",
"Van a cancelar tus monas chinas favoritas",
"Ma\xf1ana vas a coger si no te dan asco los gatos muertos",
"Ayer tenias que conocer a tu media naranja, ya ni la busques jeje",
"Los judios se van a quedar con tus propiedades",
"Te vas a morir en la tercera guerra mundial",
"Ganaras muchos bitcoins pero te los van a robar",
"Nunca seras mujer",
"Nunca sabrás de que lado masca la iguana",
"Encontraras un gloryhole con tu papá del otro lado",
"Mas vale pájaro en mano que cida en el ano",
"Ocho por ocho ya te pique el bizcocho",
"Eres el mas pendejo del Server",
"Saldrás en la radio, cómo nota de policía."

]

